### ISSUE TITLE
Interaction Failed Handler

### ISSUE THREAD

**Issue by Crispy-Cream** [GmBodhi/shandler#35]
**Is your feature request related to a problem? If so, please describe. If not, put N/A**
It's not a Shandler related problem but this will help to solve the interaction failed messages.

**Describe the solution you'd like**
Maybe if it's possible make a custom Shandler event called Interaction_Failed. Or a setting to make a custom message for button fails and slash command fails.

**Describe alternatives you've considered**
Not sure

**Additional context**
o/

**Comment by STR1KE69** [comment]
I think i have an idea but not sure if it's the best method to do it, maybe assigning a value to a variable everytime the reply method is called and in the interaction event check if the variable is undefined and if it is then emit the error handler

**Comment by GmBodhi** [comment]
I think that's not a feasible thing to do, as it's discord's side. And what if the interaction is failing because the bot is offline? And if I'm not wrong, for non-deferred interaction, it takes 3 seconds to fail, and for deferred ones, it'll take 15 minutes. So, basically, if there are a lot of interactions coming. Then it'll be an overhead for the system to handle a lot of `setTimeout`s. There will be a lot of callbacks in the event loop if you're aware of that.

**Comment by STR1KE69** [comment]
i managed to do it but didn't test the deferred interaction thing
